div = `Continue D'avancer`
let tabElement = [
`Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam deleniti rem fugit praesentium dicta quidem placeat pariatur nulla eligendi iste. Incidunt exercitationem minima praesentium animi at ipsum sint libero, deserunt cum maxime ipsa quod dicta aliquid eligendi. A enim natus unde quia odit odio dolorem blanditiis accusantium quibusdam id? Architecto fugiat, labore laborum magnam perferendis optio praesentium obcaecati dolor ratione provident, deleniti veritatis. Eaque culpa deleniti amet numquam debitis. Doloribus commodi aliquid tenetur impedit animi placeat voluptates et eligendi? Sed aut dolor laboriosam molestiae dolorum saepe quod ducimus, deleniti exercitationem blanditiis soluta, animi itaque corporis quos! Neque optio laboriosam veniam odio quia, ex dicta dignissimos error? Aut, deserunt cumque deleniti aspernatur magnam pariatur. In velit, at dolor earum vitae incidunt et quo. Veniam harum libero doloribus, officia error beatae facilis eligendi labore ut reprehenderit velit tempora, unde saepe consectetur voluptatum sed accusantium quae assumenda distinctio dolorem quam. Mollitia expedita aliquid nihil! Distinctio quam molestiae quisquam ut. Repellendus quaerat iure nisi nostrum laborum labore, odio delectus, nam ipsam nesciunt natus rem, rerum porro eius beatae minus. Et, quae cum! Officia fugiat ipsam ab officiis repellendus quae praesentium, accusantium ea inventore ut nihil cupiditate vel totam laborum odit itaque. Optio, ab eligendi!`,
`Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam porro itaque, tenetur at voluptas cupiditate! Nam, voluptatibus inventore laudantium, magnam praesentium dicta facere quibusdam, ut similique laboriosam saepe. Voluptate voluptates dignissimos sapiente possimus nulla ad aliquam libero aspernatur odit. Doloribus odio, assumenda et, dolores officiis officia animi minus obcaecati voluptatibus cupiditate enim numquam tempora? Quidem veritatis, perferendis omnis dolore sed voluptatibus nostrum harum modi architecto, autem eum vel? Dolore, sint! Nam, repellendus qui? Enim delectus reprehenderit aperiam quam dolore harum explicabo est aut, dolorem laboriosam consequatur necessitatibus, saepe ex labore non placeat a voluptate odit? Illum, recusandae culpa? Nam dolor pariatur eum repellendus rerum aliquid, dolore est? Accusamus ex laboriosam consequatur cupiditate, amet sint, fugiat tempore at excepturi, recusandae sapiente voluptatibus quo perspiciatis fugit quasi possimus illo libero repellendus voluptatum neque odio sunt iste. Repudiandae impedit quod nemo sed totam laborum sint qui rem maxime, laboriosam officiis laudantium veniam provident commodi quasi fugiat odio quidem exercitationem asperiores hic quibusdam libero itaque quis ducimus. Quod at delectus dolor illum recusandae eveniet aperiam non similique ipsum velit earum animi praesentium aliquam quo eos beatae quos, accusantium hic possimus. Unde optio corporis doloribus. In natus aliquid esse aut, laboriosam nulla quo facilis eius!`,
`Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod ad possimus unde iste aperiam, voluptas eligendi magni! Repellat enim error distinctio iste voluptates nulla quidem, quis ipsum ad accusantium optio ab aspernatur non delectus natus facere labore perspiciatis quaerat quam aliquid fugiat corrupti necessitatibus a? Perspiciatis sunt ipsum veritatis officiis consectetur, dolor similique, rem modi facilis ea ratione aut aliquam vel dolorem quod ab distinctio, esse vero voluptatibus ullam perferendis recusandae quos hic corrupti. Cupiditate odio culpa nostrum at neque provident dignissimos itaque, quisquam asperiores esse maiores, magnam, sit consequuntur corrupti voluptate voluptatum vitae. Obcaecati aliquid molestiae similique sit quaerat mollitia eius vel officiis amet repellat voluptate sequi, quae facere accusamus consectetur cumque? Vel velit perferendis nemo dolorum obcaecati quis consectetur facere doloremque, suscipit, eaque dolorem alias officiis nam quibusdam sunt eius? Animi veritatis repudiandae fugiat ad vitae placeat at! Rerum omnis nemo obcaecati doloribus consequuntur commodi necessitatibus fugit, consectetur, enim blanditiis eaque quas tempore, sint atque dignissimos quasi similique error accusantium libero expedita! Voluptatem repellat eos dignissimos tenetur! Facere cumque deleniti doloremque libero ea nisi, mollitia id rerum quos perferendis omnis porro totam corporis eveniet aliquid ut consectetur blanditiis quia dicta eum, repellat nulla nam fugit inventore. Distinctio, praesentium.`,
`Lorem ipsum dolor, sit amet consectetur adipisicing elit. Provident sapiente laborum asperiores dolore ducimus perferendis repellendus quidem ad perspiciatis, aut soluta iusto eos tempore exercitationem eum dolor animi. Doloremque, voluptatum reiciendis? Reprehenderit necessitatibus totam ad nam dicta cum. Voluptas nesciunt laudantium quam, amet, autem adipisci tempore, in voluptate dolorem distinctio voluptatem facilis officia ut incidunt ad molestias perferendis. Reprehenderit mollitia odit aliquid ut. Quod reiciendis beatae tempore nam illum cupiditate magnam voluptate non fugit nisi, odio quaerat quia culpa libero maiores eos incidunt reprehenderit! Eligendi veniam fugit, iste voluptatum ab minima provident sunt, eveniet atque ducimus omnis ad ea quam, sed aut tenetur architecto praesentium neque autem corporis ratione ex modi. Optio illum quo, quae saepe minima quibusdam ullam nulla distinctio itaque officia nam, neque nisi sed voluptas, in praesentium rem! Cumque, aut. Cupiditate doloribus, tempore aliquid laborum iusto esse possimus vel temporibus molestias numquam! Eius deleniti officiis fugit reprehenderit consequuntur repellat dicta facilis consectetur deserunt voluptatem, ducimus iusto enim nulla aut explicabo, laboriosam, sequi totam quibusdam beatae fugiat voluptatum quas id sed incidunt? Ex non numquam iusto? Doloribus laborum mollitia quae veniam harum, accusamus consectetur suscipit? Et possimus corporis voluptatem voluptatibus amet. Asperiores, est expedita consequatur voluptatem laudantium non.`,
`Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus ratione ipsam eius beatae nemo laudantium debitis culpa voluptates delectus molestias? Consequatur, impedit beatae. Eaque ex, blanditiis nihil sit consectetur praesentium sed. Incidunt doloribus tenetur, aperiam voluptatibus esse quo fugiat veniam, vero sapiente autem harum asperiores sequi enim repudiandae corporis voluptas architecto quia officiis consequuntur perspiciatis voluptate natus magni repellendus? Cumque ratione accusantium natus ex modi repellendus consectetur repudiandae? Temporibus impedit, tempore asperiores dolores nam similique praesentium natus molestiae rem velit, voluptatem ratione aliquid necessitatibus nostrum! Quidem, ipsam sapiente! Atque dignissimos maiores in non sequi. Possimus non temporibus quaerat illum asperiores natus saepe eveniet reprehenderit maxime odio totam quidem, fugiat illo quibusdam praesentium laborum modi voluptatum suscipit dolorem repudiandae, eligendi ipsam assumenda quisquam. Possimus ut ratione, eligendi et, illum eius suscipit officia deserunt odit eos nostrum debitis vero molestias aut nisi quae enim beatae ab, reiciendis iure. Sint quam, dolor esse atque asperiores ipsum praesentium, maxime incidunt molestiae ad enim aliquam architecto. Accusamus inventore placeat in recusandae cupiditate, qui voluptatibus rem quia optio mollitia, molestiae ad beatae ipsa, alias esse quidem illo quod. Nostrum odit, officiis cumque velit iusto incidunt ut! Eius dolore enim at doloribus eligendi laudantium eos ipsam nisi?`]
container = document.querySelector('.container')
let count = 0
container.addEventListener('scroll', (e)=>{
  // console.log(document.documentElement)
  // console.log(e.currentTarget.scrollTop)
  let scrollTop = e.currentTarget.scrollTop;
  let scrollHeight = e.currentTarget.scrollHeight;
  let clientHeight = e.currentTarget.clientHeight;
  let clientWidth = e.currentTarget.clientWidth;
  console.log('result',e.currentTarget.scrollTop + e.currentTarget.clientHeight)
  console.log('scrollHeight :',e.currentTarget.scrollHeight,'scrollTop :',e.currentTarget.scrollTop,'ClientHeight', e.currentTarget.clientHeight,'ClientWidth', e.currentTarget.clientWidth)
  
  if(e.currentTarget.clientHeight + e.currentTarget.scrollTop >= e.currentTarget.clientHeight ) {
    count = count == tabElement.length -1 ? 0 : count+1
    console.log(count)
    container.textContent += tabElement[count]
  }

})

window.addEventListener('DOMContentLoaded', function(e){
  console.log(count);
  container.textContent = tabElement[count]


})